// Words for the owner's admin area. Kept apart from the public copy, but with the same voice.
export const adminCopy = {
  pageTitle: 'Admin',
  skipLink: 'Skip to main content',
  brandLabel: 'Byte-Sized Buddies admin, dashboard',
  navLabel: 'Admin',
  nav: { dashboard: 'Dashboard', tickets: 'Tickets', inbox: 'Contact exchange', signOut: 'Sign out' },
  checking: 'Checking that you are signed in.',
  notConfigured:
    "The database isn't connected yet. Follow the steps in docs/DEPLOY.md, then restart the site.",
  login: {
    title: 'Sign in',
    intro: 'This area is for the owner of Byte-Sized Buddies.',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    signingIn: 'Signing in',
    wrong: "That email or password didn't work.",
    problem: 'Something went wrong. Please try again in a few minutes.',
    reasons: {
      signin: 'Please sign in to continue.',
      expired: 'Please sign in again.',
      notowner: "This account can't use the admin area.",
      signedout: 'You are signed out.',
    },
    missingEmail: 'Please type your email.',
    missingPassword: 'Please type your password.',
  },
  dashboard: {
    title: 'Dashboard',
    loading: 'Loading your counts.',
    error: "We couldn't load your counts. Please refresh the page.",
    newTickets: (n: number) => `${n} new ${n === 1 ? 'ticket' : 'tickets'}`,
    inProgress: (n: number) => `${n} ${n === 1 ? 'ticket' : 'tickets'} in progress`,
    newRequests: (n: number) =>
      n === 1 ? '1 new request from a senior home' : `${n} new requests from senior homes`,
    nextHeading: 'Next steps',
    nextTickets: 'Answer the new questions',
    nextRequests: 'Reply to the senior home requests',
    nextNothing: 'Nothing is waiting right now.',
    open: 'Open',
  },
  words: {
    urgency: { whenever: 'Whenever', this_week: 'This week', before_next_visit: 'Before the next visit' },
    device: {
      iphone: 'iPhone',
      android: 'Android phone',
      tablet: 'Tablet',
      computer: 'Computer',
      not_sure: 'Not sure',
    } as Record<string, string>,
    ticketStatus: { new: 'New', in_progress: 'In progress', answered: 'Answered', closed: 'Closed' },
    requestStatus: { new: 'New', replied: 'Replied', scheduled: 'Scheduled', closed: 'Closed' },
    none: 'Not given',
    noFacility: 'No facility given',
  },
  tickets: {
    title: 'Tickets',
    filterLabel: 'Show tickets that are',
    empty: 'No tickets here.',
    loading: 'Loading tickets.',
    loadError: "We couldn't load the tickets. Please refresh the page.",
    back: 'Back to tickets',
    question: 'Question',
    from: 'From',
    facility: 'Facility',
    email: 'Email',
    device: 'Device',
    urgency: 'How soon',
    asked: 'Asked',
    privateLink: 'Private answer link',
    privateLinkHelp: 'This is the page the person sees. Only they and you have the link.',
    openAsPerson: 'Open it as the person sees it',
    copy: 'Copy link',
    copied: 'Link copied.',
    notes: 'Private notes',
    notesHelp: 'Only you can see these.',
    saveNotes: 'Save notes',
    notesSaved: 'Notes saved.',
    answerHeading: 'Answer',
    answerLabel: 'Your answer',
    answerHelp: 'You can use **bold**, lists, and links. Pictures are not shown.',
    videoLabel: 'YouTube link or video code (optional)',
    videoHelp: 'Paste the address of an unlisted or public YouTube video.',
    videoBad: "That doesn't look like a YouTube link. Please check it.",
    previewHeading: 'Preview',
    previewEmpty: 'Your answer will show here as you type.',
    saveDraft: 'Save draft',
    draftSaved: 'Draft saved. The person cannot see it yet.',
    sendAnswer: 'Send answer',
    answeredWarning: 'This ticket is already answered. Changes you save are visible to the person right away.',
    needAnswer: 'Please write an answer or add a YouTube video first.',
    answerSent: 'Answer sent. The person can read it at their private link.',
    answerSentEmailFailed: 'The answer is saved, but the email could not be queued. Send the private link by hand.',
    emailQueued: 'An email with the link is queued.',
    noEmail: 'No email was given, so give the person their private link yourself.',
    confirmSendTitle: 'Send this answer?',
    confirmSendText: 'The person will be able to read it at their private link right away.',
    confirmSendEmail: 'We will also queue an email to them.',
    confirmCancel: 'Cancel',
    markInProgress: 'Mark in progress',
    close: 'Close ticket',
    reopen: 'Reopen',
    statusChanged: (label: string) => `Ticket marked ${label}.`,
    delete: 'Delete ticket',
    confirmDeleteTitle: 'Delete this ticket?',
    confirmDeleteText: 'This is permanent. The question, notes, and answer will be gone, and the private link will stop working.',
    deleted: 'Ticket deleted.',
    saveError: "That didn't save. Please try again.",
    actionsHeading: 'Ticket status',
  },
  inbox: {
    title: 'Contact exchange',
    requestsHeading: 'Requests from senior homes',
    gmailNote: 'Emails from your Gmail will show here once the Gmail bridge is set up.',
    filterLabel: 'Show requests that are',
    empty: 'No requests here.',
    loading: 'Loading requests.',
    loadError: "We couldn't load the requests. Please refresh the page.",
    back: 'Back to requests',
    contact: 'Contact',
    facility: 'Facility',
    role: 'Role',
    email: 'Email',
    phone: 'Phone',
    learners: 'Approximate learners',
    devices: 'Devices',
    times: 'Best days and times',
    message: 'Anything else',
    received: 'Received',
    notes: 'Private notes',
    notesHelp: 'Only you can see these.',
    saveNotes: 'Save notes',
    notesSaved: 'Notes saved.',
    statusHeading: 'Mark this request as',
    statusChanged: (label: string) => `Request marked ${label}.`,
    replyGmail: 'Reply from Gmail instead',
    replyNote: 'Opens in a new tab.',
    replySubject: 'Thank you for reaching out to Byte-Sized Buddies',
    delete: 'Delete request',
    confirmDeleteTitle: 'Delete this request?',
    confirmDeleteText: 'This is permanent. The details and your notes will be gone.',
    deleted: 'Request deleted.',
    saveError: "That didn't save. Please try again.",
    confirmCancel: 'Cancel',
  },
} as const;

export function formatWhen(iso: string | null | undefined): string {
  if (!iso) return '';
  return new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
}
