// Words for the owner's admin area. Kept apart from the public copy, but with the same voice.
export const adminCopy = {
  pageTitle: 'Admin',
  skipLink: 'Skip to main content',
  brandLabel: 'Byte-Sized Buddies admin, dashboard',
  navLabel: 'Admin',
  nav: { dashboard: 'Dashboard', tickets: 'Tickets', inbox: 'Contact exchange', lessons: 'Lessons', present: 'Present', remote: 'Remote', signOut: 'Sign out' },
  checking: 'Checking that you are signed in.',
  notConfigured:
    "The database isn't connected yet. Follow the steps in docs/DEPLOY.md, then restart the site.",
  login: {
    title: 'Sign in',
    intro: 'This area is for the owner of Byte-Sized Buddies.',
    email: 'Email',
    password: 'Password',
    submit: 'Sign in',
    signingIn: 'Signing in',
    wrong: "That email or password didn't work.",
    problem: 'Something went wrong. Please try again in a few minutes.',
    reasons: {
      signin: 'Please sign in to continue.',
      expired: 'Please sign in again.',
      notowner: "This account can't use the admin area.",
      signedout: 'You are signed out.',
    },
    missingEmail: 'Please type your email.',
    missingPassword: 'Please type your password.',
  },
  dashboard: {
    title: 'Dashboard',
    loading: 'Loading your counts.',
    error: "We couldn't load your counts. Please refresh the page.",
    newTickets: (n: number) => `${n} new ${n === 1 ? 'ticket' : 'tickets'}`,
    inProgress: (n: number) => `${n} ${n === 1 ? 'ticket' : 'tickets'} in progress`,
    newRequests: (n: number) =>
      n === 1 ? '1 new request from a senior home' : `${n} new requests from senior homes`,
    nextHeading: 'Next steps',
    nextTickets: 'Answer the new questions',
    nextRequests: 'Reply to the senior home requests',
    nextNothing: 'Nothing is waiting right now.',
    open: 'Open',
  },
  words: {
    urgency: { whenever: 'Whenever', this_week: 'This week', before_next_visit: 'Before the next visit' },
    device: {
      iphone: 'iPhone',
      android: 'Android phone',
      tablet: 'Tablet',
      computer: 'Computer',
      not_sure: 'Not sure',
    } as Record<string, string>,
    ticketStatus: { new: 'New', in_progress: 'In progress', answered: 'Answered', closed: 'Closed' },
    requestStatus: { new: 'New', replied: 'Replied', scheduled: 'Scheduled', closed: 'Closed' },
    none: 'Not given',
    noFacility: 'No facility given',
  },
  tickets: {
    title: 'Tickets',
    filterLabel: 'Show tickets that are',
    empty: 'No tickets here.',
    loading: 'Loading tickets.',
    loadError: "We couldn't load the tickets. Please refresh the page.",
    back: 'Back to tickets',
    question: 'Question',
    from: 'From',
    facility: 'Facility',
    email: 'Email',
    device: 'Device',
    urgency: 'How soon',
    asked: 'Asked',
    privateLink: 'Private answer link',
    privateLinkHelp: 'This is the page the person sees. Only they and you have the link.',
    openAsPerson: 'Open it as the person sees it',
    copy: 'Copy link',
    copied: 'Link copied.',
    notes: 'Private notes',
    notesHelp: 'Only you can see these.',
    saveNotes: 'Save notes',
    notesSaved: 'Notes saved.',
    answerHeading: 'Answer',
    answerLabel: 'Your answer',
    answerHelp: 'You can use **bold**, lists, and links. Pictures are not shown.',
    videoLabel: 'YouTube link or video code (optional)',
    videoHelp: 'Paste the address of an unlisted or public YouTube video.',
    videoBad: "That doesn't look like a YouTube link. Please check it.",
    previewHeading: 'Preview',
    previewEmpty: 'Your answer will show here as you type.',
    saveDraft: 'Save draft',
    draftSaved: 'Draft saved. The person cannot see it yet.',
    sendAnswer: 'Send answer',
    answeredWarning: 'This ticket is already answered. Changes you save are visible to the person right away.',
    needAnswer: 'Please write an answer or add a YouTube video first.',
    answerSent: 'Answer sent. The person can read it at their private link.',
    answerSentEmailFailed: 'The answer is saved, but the email could not be queued. Send the private link by hand.',
    emailQueued: 'An email with the link is queued.',
    noEmail: 'No email was given, so give the person their private link yourself.',
    confirmSendTitle: 'Send this answer?',
    confirmSendText: 'The person will be able to read it at their private link right away.',
    confirmSendEmail: 'We will also queue an email to them.',
    confirmCancel: 'Cancel',
    markInProgress: 'Mark in progress',
    close: 'Close ticket',
    reopen: 'Reopen',
    statusChanged: (label: string) => `Ticket marked ${label}.`,
    delete: 'Delete ticket',
    confirmDeleteTitle: 'Delete this ticket?',
    confirmDeleteText: 'This is permanent. The question, notes, and answer will be gone, and the private link will stop working.',
    deleted: 'Ticket deleted.',
    saveError: "That didn't save. Please try again.",
    actionsHeading: 'Ticket status',
  },
  lessons: {
    title: 'Lessons',
    loading: 'Loading lessons.',
    loadError: "We couldn't load the lessons. Please refresh the page.",
    empty: 'You have no lessons yet. Make a new one, or import a kit.',
    newLesson: 'New lesson',
    importKit: 'Import a kit',
    backup: 'Download a backup of all lessons',
    backupDone: 'Backup downloaded.',
    storageUsed: (used: string) => `Storage used: ${used} of about 1 GB`,
    storageLabel: 'Storage used',
    draft: 'Draft',
    published: 'Published',
    updated: 'Updated',
    edit: 'Edit',
    preview: 'Preview',
    viewPublic: 'View public page',
    publish: 'Publish',
    unpublish: 'Unpublish',
    published_ok: (title: string) => `"${title}" is published. Anyone can see it now.`,
    unpublished_ok: (title: string) => `"${title}" is a draft again. Only you can see it.`,
    present: 'Present',
    exportKit: 'Download as a kit (zip)',
    exporting: 'Making the zip',
    exportDone: 'Kit downloaded.',
    exportFailed: "We couldn't make the zip. Some files could not be fetched.",
    delete: 'Delete',
    confirmDeleteTitle: 'Delete this lesson?',
    confirmDeleteText: 'This is permanent. The lesson and all its files will be gone, and its public page will stop working.',
    typeTitle: 'Type the lesson title to confirm',
    deleted: (title: string) => `"${title}" was deleted.`,
    saveError: "That didn't work. Please try again.",
    cancel: 'Cancel',
    importHeading: 'Import a kit',
    importHelp: 'Choose kit.json together with every PDF and image it names. Select them all at once, or drag them here.',
    chooseFiles: 'Choose files',
    dropHere: 'Or drop the files here',
    kitMissing: 'Please include kit.json with the files you choose.',
    kitUnreadable: "kit.json can't be read. It has a typing mistake. Check commas, quote marks, and brackets.",
    problems: 'Please fix these first:',
    warningsHeading: 'Things to look at (you can still import)',
    saveDraft: 'Save as draft',
    saving: 'Saving',
    uploading: (n: number, total: number) => `Uploading file ${n} of ${total}`,
    replaceTitle: 'This address is already used',
    replaceText: 'A lesson with this web address already exists. Replacing it swaps in the new slides and files, and sets it back to a draft so you can check it before it goes public.',
    replaceButton: 'Replace this lesson',
    imported: (title: string) => `"${title}" is saved as a draft. Review it, then press Publish.`,
    clear: 'Start over',
    presentLater: '',
  },
  lessonEdit: {
    titleNew: 'New lesson',
    titleEdit: 'Edit lesson',
    titlePreview: 'Lesson preview',
    present: 'Present',
    back: 'Back to lessons',
    loading: 'Loading the lesson.',
    notFound: "We can't find that lesson.",
    save: 'Save lesson',
    saving: 'Saving',
    saved: 'Lesson saved.',
    savedDraft: 'Lesson saved as a draft. Open it from Lessons when you are ready to publish.',
    fixFirst: 'Please fix these before saving:',
    uploading: (n: number, total: number) => `Uploading file ${n} of ${total}`,
    aboutHeading: 'About the lesson',
    fields: {
      title: 'Title',
      slug: 'Web address (slug)',
      slugHelp: 'Lowercase letters, numbers, and dashes. It becomes part of the lesson link. It is made from the title until you edit it.',
      slugChange: 'Changing the address changes the lesson link.',
      week: 'Week number',
      summary: 'One-line summary',
      topic: 'Topic',
      devices: 'Devices',
      level: 'Level',
      duration: 'Length in minutes',
      license: 'License',
    },
    deviceOptions: [
      { value: 'iphone', label: 'iPhone' },
      { value: 'android', label: 'Android' },
      { value: 'any', label: 'Any device' },
    ],
    levelOptions: [
      { value: 'beginner', label: 'Beginner' },
      { value: 'intermediate', label: 'Intermediate' },
    ],
    objectivesHeading: "What learners will be able to do",
    objectivesHelp: 'One short line for each thing.',
    objective: (n: number) => `Objective ${n}`,
    addObjective: 'Add an objective',
    guideHeading: 'Teacher guide',
    guideLabel: 'Teacher guide (markdown)',
    guideHelp: 'Write the minute-by-minute guide. Pictures from other websites are not shown.',
    scriptHeading: 'Video script',
    scriptLabel: 'Video script (markdown)',
    scriptHelp: 'Only you see this. The studio shows it on the teleprompter.',
    preview: 'Preview',
    previewEmpty: 'Your text will show here as you type.',
    slidesHeading: 'Slides',
    slidesHelp: 'Each slide is a few lines of data. The list below shows them in order. You can also edit the text directly.',
    slidesJsonLabel: 'Slides (JSON text)',
    slidesOk: (n: number) => `The slides look good. ${n} ${n === 1 ? 'slide' : 'slides'}.`,
    slidesList: 'Slide order',
    slideOf: (n: number, layout: string, title: string) => `${n}. ${layout}: ${title || '(no title)'}`,
    slidePreview: 'Preview of the chosen slide',
    chooseSlide: 'Choose a slide to preview',
    addSlide: 'Add a slide',
    addSlideLayout: 'Kind of slide',
    moveUp: 'Move up',
    moveDown: 'Move down',
    remove: 'Remove',
    filesHeading: 'Files',
    filesHelp: 'PDF files up to 10 MB. Pictures: PNG, JPG, WebP, or SVG.',
    slots: {
      worksheet: 'Worksheet (PDF)',
      handout: 'Handout (PDF)',
      answer_key: 'Answer key (PDF)',
      teacher_guide_pdf: 'Teacher guide (PDF)',
    },
    currentFile: 'Current file',
    noFile: 'No file yet',
    removeFile: 'Remove this file when I save',
    willRemove: 'This file will be removed when you save.',
    chosen: 'Chosen',
    imagesLabel: 'Slide pictures',
    imagesHelp: 'The names must match the picture names used in your slides.',
    videosHeading: 'Videos',
    videosHelp: 'Add the YouTube links in the order they should play. Upload videos to YouTube yourself first.',
    videoLink: (n: number) => `YouTube link or code ${n}`,
    videoLabel: (n: number) => `Label ${n} (for example Opener)`,
    addVideo: 'Add a video',
    videoBad: "That doesn't look like a YouTube link.",
    errors: {
      title: 'Please give the lesson a title.',
      slug: 'The web address should be lowercase letters, numbers, and single dashes.',
      week: 'The week number should be a whole number from 1 to 200.',
      duration: 'The length should be a whole number from 5 to 240.',
      devices: 'Choose at least one device.',
      slugTaken: 'Another lesson already uses that web address. Please choose a different one.',
    },
  },
  present: {
    title: 'Present',
    pickIntro: 'Choose a lesson to present. Slides open in two windows: one for you, with notes, and one for the screen.',
    pickEmpty: 'You have no lessons with slides yet.',
    pickButton: 'Present this lesson',
    loading: 'Loading the lesson.',
    notFound: "We can't find that lesson.",
    noSlides: 'This lesson has no slides yet. Add some in the lesson editor.',
    back: 'Back to lessons',
    controlsLabel: 'Presenter controls',
    prev: 'Back',
    next: 'Next',
    current: 'Now showing',
    upNext: 'Up next',
    endOfLesson: 'That is the last slide.',
    notes: 'Speaker notes',
    noNotes: 'No notes for this slide.',
    strip: 'All slides',
    stripItem: (n: number, title: string) => `Go to slide ${n}: ${title}`,
    openAudience: 'Open audience window',
    focusAudience: 'Show audience window',
    audienceOpen: 'Audience window: open',
    audienceClosed: 'Audience window: not open',
    audienceBlocked: 'Your browser blocked the new window. Allow pop-ups for this site, then try again.',
    audienceHelp: 'Drag the audience window to the TV or projector, then press F in it (or double-click it) for full screen.',
    blank: 'Blank screen',
    unblank: 'Show the slide',
    blankOn: 'The audience screen is blank.',
    fullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
    single: 'Present in this window',
    singleBack: 'Back to controls',
    print: 'Download slides as PDF',
    printHelp: 'A backup in case Wi-Fi fails: print or save the slides as a PDF.',
    remoteHeading: 'Phone remote',
    remoteCode: 'Remote code',
    remoteHelp: 'On your phone, open Admin, Remote, and type this code. Use your phone as a hotspot if the Wi-Fi is bad, or use the keyboard.',
    remoteOffline: 'The phone remote is off until the database is ready for it (docs/DEPLOY.md, Step 12). The keyboard still works.',
    keys: 'Keys: arrow keys or Space for next, Home and End, B for blank, F for full screen.',
    clockHeading: 'Lesson clock',
    clockStart: 'Start the clock',
    clockPause: 'Pause the clock',
    clockReset: 'Reset the clock',
    clockWarn: '5 minutes left. Start wrapping up.',
    clockOver: 'Time is up.',
    clockFine: 'Plenty of time.',
    tryTimerStart: (m: number) => `Start the ${m}-minute practice timer`,
    tryTimerPause: 'Pause the practice timer',
    slideCounter: (n: number, total: number) => `Slide ${n} of ${total}`,
    ended: 'The presenter window was closed.',
    imagesPreloaded: 'Pictures are saved in this browser, so the slides still work if the Wi-Fi drops.',
  },
  audience: {
    waiting: 'Waiting for the presenter window.',
    waitingHelp: 'Open this screen from the presenter window: press Open audience window.',
    ended: 'The presentation has ended. You can close this window.',
    fullscreenHint: 'Press F or double-click for full screen',
    title: 'Slides',
  },
  remote: {
    title: 'Remote',
    intro: 'Type the 4-letter code shown on the presenter screen.',
    codeLabel: 'Code',
    codeHelp: 'Four letters, for example KFPD.',
    connect: 'Connect',
    badCode: 'Please type four letters. The code never has I, L, or O.',
    status: 'Status',
    connecting: 'Connecting',
    looking: 'Connected. Looking for the presenter',
    live: 'Connected to the presenter',
    noPresenter: "Connected, but no presenter found for that code. Check the code, and make sure the presenter window is open.",
    retrying: 'Disconnected. Trying again',
    denied: "The remote isn't allowed yet. The database needs one more step (docs/DEPLOY.md, Step 12).",
    ended: 'The presenter window was closed. The code no longer works.',
    reconnect: 'Reconnect',
    newCode: 'Use a different code',
    back: 'Back',
    next: 'Next',
    blank: 'Blank screen',
    unblank: 'Show the slide',
    timerStart: 'Start the clock',
    timerPause: 'Pause the clock',
    timeLeft: 'Time left',
    notes: 'Notes',
    noNotes: 'No notes for this slide.',
    upNext: 'Up next',
    slide: (n: number, total: number) => `Slide ${n} of ${total}`,
    awake: 'Your screen will stay on while this page is open.',
    awakeNo: "This phone can't keep the screen on. Change its sleep setting if it goes dark.",
    keepOpen: 'Keep this page open.',
  },
  inbox: {
    title: 'Contact exchange',
    requestsHeading: 'Requests from senior homes',
    gmailNote: 'Emails from your Gmail will show here once the Gmail bridge is set up.',
    filterLabel: 'Show requests that are',
    empty: 'No requests here.',
    loading: 'Loading requests.',
    loadError: "We couldn't load the requests. Please refresh the page.",
    back: 'Back to requests',
    contact: 'Contact',
    facility: 'Facility',
    role: 'Role',
    email: 'Email',
    phone: 'Phone',
    learners: 'Approximate learners',
    devices: 'Devices',
    times: 'Best days and times',
    message: 'Anything else',
    received: 'Received',
    notes: 'Private notes',
    notesHelp: 'Only you can see these.',
    saveNotes: 'Save notes',
    notesSaved: 'Notes saved.',
    statusHeading: 'Mark this request as',
    statusChanged: (label: string) => `Request marked ${label}.`,
    replyGmail: 'Reply from Gmail instead',
    replyNote: 'Opens in a new tab.',
    replySubject: 'Thank you for reaching out to Byte-Sized Buddies',
    delete: 'Delete request',
    confirmDeleteTitle: 'Delete this request?',
    confirmDeleteText: 'This is permanent. The details and your notes will be gone.',
    deleted: 'Request deleted.',
    saveError: "That didn't save. Please try again.",
    confirmCancel: 'Cancel',
  },
} as const;

export function formatWhen(iso: string | null | undefined): string {
  if (!iso) return '';
  return new Date(iso).toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
}
