// All user-facing words for the shared page frame live here, so they can be translated later.
export const copy = {
  siteName: 'Byte-Sized Buddies',
  tagline: 'Learn it. Try it. Keep it.',
  skipLink: 'Skip to main content',
  logoHomeLabel: 'Byte-Sized Buddies, home',
  readingTools: {
    label: 'Reading tools',
    textSize: 'Text size',
    sizes: [
      { value: 'normal', label: 'Normal' },
      { value: 'larger', label: 'Larger' },
      { value: 'largest', label: 'Largest' },
    ],
    contrast: 'High contrast',
    spacing: 'Roomy spacing',
    reset: 'Reset',
    on: 'On',
    off: 'Off',
  },
  readAloud: {
    start: 'Read this aloud',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    speed: 'Reading speed',
    speeds: [
      { value: '0.8', label: 'Slower' },
      { value: '1', label: 'Normal' },
      { value: '1.2', label: 'Faster' },
    ],
    unsupported: 'Your browser can not read aloud. You can try Safari or Chrome.',
    help: 'Your device reads the words out loud. Nothing is sent anywhere.',
    reading: 'Reading aloud',
    paused: 'Paused',
    done: 'Finished reading.',
  },
  nav: {
    label: 'Main',
    items: [
      { label: 'Lessons', href: '/lessons' },
      { label: 'For senior homes', href: '/for-senior-homes' },
      { label: 'Ask a question', href: '/ask' },
      { label: 'Teach it yourself', href: '/teach' },
      { label: 'About', href: '/about' },
    ],
    visit: { label: 'Request a visit', href: '/for-senior-homes#contact' },
    menuOpen: 'Menu',
    menuClose: 'Close menu',
  },
  footer: {
    line: 'Byte-Sized Buddies · Free to print and share · [YOUR WEBSITE]',
    studentLed: 'Student-led volunteer project.',
    mission: 'Free, patient technology lessons for older adults, and free materials for anyone who wants to teach them.',
    exploreHeading: 'Explore',
    exploreLabel: 'Explore the site',
    linksHeading: 'About this site',
    linksLabel: 'About this site',
    links: [
      { label: 'Privacy', href: '/privacy' },
      { label: 'License', href: '/license' },
      { label: 'Questions and answers', href: '/faq' },
      { label: 'Stay safe online', href: '/stay-safe' },
      { label: 'Visit-day checklist', href: '/visit-checklist' },
      { label: 'Photo and video consent', href: '/consent-form' },
      { label: 'Owner sign in', href: '/admin' },
    ],
  },
  form: {
    required: '(required)',
    optional: '(optional)',
    errorPrefix: 'Problem:',
    summaryTitle: 'Please fix these before sending:',
    sending: 'Sending',
    notConnected: "This form isn't connected yet, so nothing was sent. Please check back soon.",
    privacyHelper: "Please don't include passwords, medical details, or bank information.",
    errors: {
      name: 'Please tell us your name.',
      facility: 'Please tell us the name of your facility.',
      email: 'Please enter an email like name@example.com.',
      questionShort: 'Please write at least 5 characters.',
      questionLong: 'Please keep your question under 2,000 characters.',
    },
  },
  mission:
    'Free, patient, hands-on technology lessons for older adults, and free materials for anyone who wants to teach them.',
  home: {
    title: 'Byte-Sized Buddies',
    description:
      'Free, patient, hands-on technology lessons for older adults, and free materials for anyone who wants to teach them.',
    heroButtons: { visit: 'Request a visit', lessons: 'Get free lessons' },
    heroKicker: 'Free technology lessons for older adults',
    facts: [
      { icon: 'check', title: 'Free, always', text: 'No cost for senior homes, learners, or teachers.' },
      { icon: 'play', title: 'About 45 minutes', text: 'One small, useful skill each visit.' },
      { icon: 'book', title: 'Large print', text: 'A handout for every learner to keep.' },
    ],
    visit: {
      heading: 'How a visit works',
      steps: [
        { title: 'Learn it.', text: 'We start with a short, friendly slideshow. One idea at a time.' },
        { title: 'Try it.', text: 'Everyone practices on their own device, with help beside them.' },
        { title: 'Keep it.', text: 'Each person takes home a large-print handout to remember what they learned.' },
      ],
    },
    lessons: {
      heading: 'What you can learn',
      intro: 'Each lesson teaches one real thing, like calling a friend or sharing a photo. Every lesson is free to download, print, and teach.',
      all: 'See all lessons',
      emptyTitle: 'Our first lessons are on the way',
      emptyText: 'Every lesson will be free to download, print, and share. Please check back soon.',
    },
    homes: {
      heading: 'For senior homes',
      text: "We bring everything. You provide a space, a TV or projector if you have one, and a few residents who want to learn. There's no cost, ever.",
      needHeading: 'What we need from you',
      needs: ['A room', 'A screen or TV (optional)', 'Wi-Fi, if you have it', 'A staff contact person'],
      button: 'Ask about a visit',
      more: 'How a visit works',
    },
    free: {
      heading: 'Free for everyone',
      text: 'Want to teach these lessons in your community? Everything here is free to download, print, and adapt. Read the teacher guide, bring a friend, and tell us how it went.',
      button: 'Teach it yourself',
    },
    promise: {
      heading: 'A promise to families and staff',
      intro: 'Learning should feel safe. These rules are part of every lesson we teach.',
      moreLinks: [
        { label: 'Stay safe online', href: '/stay-safe' },
        { label: 'Questions and answers', href: '/faq' },
      ],
      icons: ['alert', 'phone', 'video', 'check'],
      items: [
        'We never ask learners to type a real password in class.',
        'We use practice accounts.',
        'We take photos and video only with written consent.',
        'Our lessons are free, always.',
      ],
    },
  },
  homes: {
    title: 'For senior homes',
    description:
      'What a Byte-Sized Buddies visit looks like, what we need from you, and how to ask for a visit. Every lesson is free.',
    intro:
      "We bring everything. You provide a space, a TV or projector if you have one, and a few residents who want to learn. There's no cost, ever. Lessons run about 45 minutes. Each lesson comes with a large-print handout for every learner.",
    flowHeading: 'How a visit works',
    flowIntro: 'Each visit is one lesson, about 45 minutes long.',
    flow: [
      'Welcome and a warm-up question (three minutes)',
      'Learn it: a short slideshow (10 minutes)',
      'Try it: guided practice on each person\'s own device (20 minutes)',
      'Worksheet, then teach it back to a neighbor (seven minutes)',
      'Keep it: a large-print handout and a take-home challenge (five minutes)',
    ],
    timeline: [
      { title: 'Welcome', text: 'A warm-up question, and everyone says hello.', minutes: '3 minutes' },
      { title: 'Learn it', text: 'A short slideshow. One idea at a time.', minutes: '10 minutes' },
      { title: 'Try it', text: "Guided practice on each person's own device.", minutes: '20 minutes' },
      { title: 'Worksheet', text: 'A one-page worksheet, then teach it back to a neighbor.', minutes: '7 minutes' },
      { title: 'Keep it', text: 'A large-print handout and a take-home challenge.', minutes: '5 minutes' },
    ],
    jump: 'Request a visit',
    needHeading: 'What we need from you',
    needs: ['A room', 'A screen or TV (optional)', 'Wi-Fi, if you have it', 'A staff contact person'],
    bringHeading: 'What we bring',
    bring: [
      'Everything we need, free of charge',
      'A large-print handout for every learner',
      'A short slideshow and a one-page worksheet',
      'Practice accounts, so no one types a real password',
    ],
    nextHeading: 'What happens next',
    next: [
      'Send this form. Fill in what you know; only three answers are required.',
      "We reply within two days, to the email you give us.",
      'We plan a day and time with your staff contact, then bring everything.',
    ],
    safeHeading: 'Good to know',
    safe: [
      'Every visit is free. There is nothing to sign up for.',
      'We use practice accounts, so no one types a real password.',
      'We take photos only with written consent from the person and your facility.',
    ],
    moreHeading: 'More for staff and families',
    moreLinks: [
      { label: 'Questions and answers', href: '/faq' },
      { label: 'Stay safe online', href: '/stay-safe' },
      { label: 'Photo and video consent form', href: '/consent-form' },
    ],
    formHeading: 'Request a visit',
    formIntro: "Tell us a little about your community. We'll write back to plan a time.",
    fields: {
      name: 'Your name',
      facility: 'Facility name',
      role: 'Your role',
      email: 'Email',
      phone: 'Phone',
      learners: 'Approximate number of learners',
      devicesLegend: 'Devices they usually use',
      times: 'Best days and times',
      more: 'Anything else we should know',
    },
    devices: [
      { value: 'iphone', label: 'iPhone' },
      { value: 'android', label: 'Android phone' },
      { value: 'tablet', label: 'Tablet' },
      { value: 'computer', label: 'Computer' },
      { value: 'not_sure', label: 'Not sure' },
    ],
    submit: 'Send request',
    success: {
      title: 'Thank you',
      text: "We'll reply within two days. We'll write to the email you gave us.",
      again: 'Send another request',
    },
  },
  ask: {
    title: 'Ask a question',
    description:
      'Have a quick question about a device or a lesson? Ask here. Your answer appears at a private link only you have.',
    intro:
      "Have a quick question about a device or a lesson? Tell us what you're seeing. Please don't include passwords, medical details, or bank information.",
    fields: {
      name: 'Your name',
      facility: 'Facility',
      email: 'Email',
      emailHelper: 'So we can send your answer.',
      deviceLegend: 'Which device is it about?',
      urgencyLegend: 'How soon do you need an answer?',
      question: 'Your question',
      questionHelper: 'Write between 5 and 2,000 characters.',
    },
    devices: [
      { value: 'iphone', label: 'iPhone' },
      { value: 'android', label: 'Android phone' },
      { value: 'tablet', label: 'Tablet' },
      { value: 'computer', label: 'Computer' },
      { value: 'not_sure', label: 'Not sure' },
    ],
    urgency: [
      { value: 'whenever', label: 'Whenever' },
      { value: 'this_week', label: 'This week' },
      { value: 'before_next_visit', label: 'Before our next visit' },
    ],
    nextHeading: 'What happens next',
    next: [
      'Send your question. A private answer link appears right away.',
      "Save the link. It's the only way to find your answer.",
      'We reply within two days. If you give an email, we send the link there too.',
    ],
    tipsHeading: 'Tips for a good question',
    tips: [
      'Say which device it is, like an iPhone or a tablet.',
      'Tell us what you see on the screen. Copy any message word for word.',
      'Say what you were trying to do.',
      'Never include passwords or bank details.',
    ],
    submit: 'Send question',
    success: {
      title: 'We got your question',
      linkLabel: 'Your private answer link',
      save: "Save this link. It's the only way to find your answer.",
      emailNote: "If you gave an email, we'll also send the link there.",
      copy: 'Copy link',
      copied: 'Link copied.',
      copyFailed: 'Your browser could not copy it. Select the link and copy it by hand.',
      again: 'Ask another question',
    },
  },
  viewer: {
    label: 'Slides',
    previous: 'Back',
    next: 'Next',
    counter: (n: number, total: number) => `${n} of ${total}`,
    announce: (n: number, total: number, title: string) => `Slide ${n} of ${total}: ${title}`,
    progress: 'Slide progress',
    fullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
    blank: 'Blank screen',
    unblank: 'Show the slide',
    blankNote: 'The screen is blank. Press B or the button to show the slide.',
    print: 'Download slides as PDF',
    keys: 'Tip: click the slide, then use the arrow keys, Space, Home, End, B for blank, and F for full screen.',
    timerStart: (minutes: number) => `Start ${minutes}-minute timer`,
    timerPause: 'Pause timer',
    timerReset: 'Reset timer',
    timerDone: 'Time is up.',
    minutes: 'minutes',
    notes: 'Speaker notes',
    noNotes: 'No notes for this slide.',
    noSlides: 'This lesson has no slides yet.',
    tryIt: 'Try it',
    missingImage: 'Picture not found',
    recapTitle: 'Today you learned',
  },
  answer: {
    title: 'Your answer',
    description: 'Read the answer to your question.',
    loading: 'Looking for your answer',
    notConfigured: "This page isn't connected yet. Please check back soon.",
    notFoundTitle: "We can't find that link",
    notFoundText:
      'The link may be missing a few letters. Try opening it again from where you saved it. You can also ask your question again.',
    askAgain: 'Ask a question',
    statusLabel: 'Status',
    status: {
      new: 'Received',
      in_progress: "We're working on it",
      answered: 'Answered',
      closed: 'Closed',
    },
    greeting: (name: string) => `Hello ${name}`,
    questionHeading: 'Your question',
    answerHeading: 'Our answer',
    waiting: "We haven't answered yet. Please come back to this page later. Your link keeps working.",
    videoTitle: 'Video answer',
    videoOpener: 'Hello',
    videoMain: 'Your answer',
    videoCloser: 'Goodbye',
    errorText: 'Something went wrong while looking for your answer. Please try again in a few minutes.',
  },
  lessons: {
    title: 'Free lessons',
    description: 'Free technology lessons for older adults. Download, print, adapt, and share.',
    intro: 'Every lesson comes with a teacher guide, a slideshow, a worksheet, and a large-print handout. All of it is free to download, print, and share.',
    emptyTitle: 'Our first lessons are on the way',
    emptyText:
      'Each lesson will come with a teacher guide, a slideshow, a worksheet, and a large-print handout. All of it will be free to download, print, and share.',
    teachButton: 'Teach it yourself',
    loading: 'Loading lessons',
    loadError: "We couldn't load the lessons. Please try again in a few minutes.",
    filterLabel: 'Show lessons for',
    chips: { all: 'All', iphone: 'iPhone', android: 'Android', beginner: 'Beginner', intermediate: 'Intermediate' },
    searchLabel: 'Search lessons',
    searchHelp: 'Type a word from the title or topic.',
    noMatches: 'No lessons match. Try a different word, or choose All.',
    count: (n: number) => `${n} ${n === 1 ? 'lesson' : 'lessons'} shown`,
    week: (n: number | null) => (n === null ? 'Lesson' : `Week ${n}`),
    minutes: (n: number) => `${n} minutes`,
    seeAll: 'See all lessons',
    topicLegend: 'Topic',
    sortLabel: 'Sort by',
    sorts: [
      { value: 'week', label: 'Week number' },
      { value: 'newest', label: 'Newest first' },
      { value: 'shortest', label: 'Shortest first' },
      { value: 'az', label: 'A to Z' },
    ],
    clear: 'Clear all choices',
    shareChoices: 'Copy a link to this list',
    shareCopied: 'Link copied. Anyone who opens it sees the same list.',
    shareFailed: 'Your browser could not copy it. Copy the address from the top of the window.',
    searchHelp2: 'Type a word from the title, topic, or what you will learn. Every word you type must match.',
    newest: 'Newest lesson',
    newestHeading: 'The newest lesson',
    newestIntro: 'Our most recent lesson, ready to teach this week.',
    openLesson: 'Open this lesson',
    chipsSummary: (n: number) => (n === 0 ? 'Showing every lesson' : `${n} ${n === 1 ? 'choice' : 'choices'} chosen`),
  },
  player: {
    play: 'Play the video',
    playParts: (n: number) => (n === 1 ? 'Play the video' : `Play the video (${n} parts)`),
    partsIntro: (labels: string[]) => `This video has ${labels.length} parts: ${labels.join(', ')}. They play one after another.`,
    privacy: 'The video plays from YouTube. Nothing loads from YouTube until you press Play.',
    part: (n: number, total: number, label: string) => `Part ${n} of ${total}${label ? `: ${label}` : ''}`,
    prev: 'Previous part',
    next: 'Next part',
    partsLabel: 'Choose a part',
    goTo: (n: number, label: string) => `Part ${n}${label ? `: ${label}` : ''}`,
    ended: 'That was the last part.',
    again: 'Watch from the start',
    captions: 'Captions are on when the video has them. Press CC in the player to turn them off.',
    frameTitle: (title: string, label: string) => `${title}${label ? `: ${label}` : ''}`,
  },
  lesson: {
    loading: 'Loading the lesson',
    notFoundTitle: "We can't find that lesson",
    notFoundText: 'The lesson may have moved, or the link may have a typing mistake. You can see every lesson in the library.',
    library: 'Go to the lessons',
    objectives: "What you'll be able to do",
    downloads: 'Downloads',
    downloadsNone: 'The downloads for this lesson are not ready yet.',
    pdf: 'PDF',
    read: 'Read',
    save: 'Save',
    extrasHeading: 'Extra practice',
    extrasIntro: 'For when there is time left over, or for learners who want more. Each one is a printable page.',
    slidesHeading: 'Preview the slides',
    videoHeading: 'Video',
    guideHeading: 'Teacher guide',
    noGuide: 'The teacher guide for this lesson is not ready yet.',
    license: 'License',
    licenseLink: 'How you may use this lesson',
    tell: 'Tell us how it went',
    printGuide: 'Print this page',
    adminDraft: 'This lesson is a draft. Only you can see it.',
    glanceHeading: 'This lesson at a glance',
    glance: {
      time: 'Time',
      level: 'Level',
      devices: 'Devices',
      bring: 'Bring',
      bringItems: 'A large-print handout and worksheet for every learner, and a laptop for the slides.',
      topic: 'Topic',
    },
    planHeading: 'Plan your visit',
    planIntro: (minutes: number) => `A ${minutes}-minute visit, one step after another. Times are a guide. Follow your learners.`,
    planMinutes: (n: number) => `${n} ${n === 1 ? 'minute' : 'minutes'}`,
    planStarts: (n: number) => (n === 0 ? 'Starts at the beginning' : `Starts at minute ${n}`),
    shareHeading: 'Share this lesson',
    shareText: 'Send the link to a friend who teaches, or to a staff member at a senior home.',
    shareButton: 'Copy the link to this lesson',
    shareCopied: 'Link copied.',
    shareFailed: 'Your browser could not copy it. Copy the address from the top of the window.',
    allFiles: 'Download everything (one zip file)',
    allFilesWorking: 'Collecting the files',
    allFilesHelp: 'One zip file with the guide, worksheet, handout, pictures, and a kit.json so another teacher can import it.',
    allFilesFailed: 'We could not collect the files. Please try each download on its own.',
    moreHeading: 'Keep going',
    previousLesson: 'Previous lesson',
    nextLesson: 'Next lesson',
    relatedHeading: 'Lessons you may like next',
    allLessons: 'See all lessons',
  },
  about: {
    title: 'About',
    description: 'Byte-Sized Buddies is a student-led volunteer project that teaches technology to older adults.',
    card: { heading: 'Want a visit?', text: 'We bring everything, and there is no cost, ever.', button: 'Request a visit', href: '/for-senior-homes#contact' },
  },
  textPage: { toc: 'On this page' },
  faq: {
    title: 'Questions and answers',
    description: 'Answers to common questions from senior homes, learners, families, and teachers.',
    card: { heading: 'Still have a question?', text: 'Ask us. Your answer appears at a private link only you have.', button: 'Ask a question', href: '/ask' },
  },
  staySafe: {
    title: 'Stay safe online',
    description: 'Calm, clear rules for phone calls, texts, email, and pop-ups. Print it and keep it by the phone.',
    printButton: 'Print this page',
    card: { heading: 'Learn it hands-on', text: 'Our lessons teach these habits with practice accounts, at your own pace.', button: 'See the free lessons', href: '/lessons' },
  },
  visitList: {
    title: 'Visit-day checklist',
    description: 'A printable checklist for volunteers: what to do before, during, and after a lesson visit.',
    intro: 'Print this and tick the boxes as you go. It matches the 45-minute lesson in every kit. Nothing you tick is saved or sent anywhere.',
    print: 'Print the checklist',
    groups: [
      {
        title: 'A week before',
        items: [
          'Confirm the day, time, and room with your staff contact.',
          'Ask how many learners are coming, and which devices they use.',
          'Read the teacher guide for this lesson all the way through.',
          'Try every step yourself on a practice account.',
          'Ask the facility about photo and video consent. Bring no camera if you do not have written consent.',
        ],
      },
      {
        title: 'The day before',
        items: [
          'Print a large-print handout and worksheet for every learner, plus a few spares.',
          'Load the slides on your laptop. Download the PDF too, in case the Wi-Fi fails.',
          'Charge your laptop, your phone, and the phone you use as the remote.',
          'Pack a charger, an extension cord, pens, and a clock you can see.',
          'Sign out of your own accounts on the practice device.',
        ],
      },
      {
        title: 'When you arrive',
        items: [
          'Arrive 20 minutes early. Say hello to your staff contact.',
          'Set up the screen. Check that the back row can read the slides.',
          'Turn off notifications on your laptop and phone.',
          'Hand out the worksheets face down, and put a pen at each seat.',
          'Check the room is quiet and comfortable. Open a window or close a door if needed.',
        ],
      },
      {
        title: 'During the lesson',
        items: [
          'Welcome everyone and ask a warm-up question (about three minutes).',
          'Learn it: show the slides, one idea at a time (about 10 minutes).',
          "Try it: guided practice on each learner's own device (about 20 minutes). Walk around and sit beside people.",
          'Worksheet and teach-back to a neighbor (about seven minutes).',
          'Keep it: hand out the large-print handout and explain the take-home challenge (about five minutes).',
          'Remind everyone of the safety rule: hang up, call the number on your card, call someone you trust.',
        ],
      },
      {
        title: 'Before you leave',
        items: [
          'Thank your staff contact and ask what went well.',
          'Collect any papers and pens. Leave the room as you found it.',
          'Agree on a date for the next visit, if there is one.',
        ],
      },
      {
        title: 'Afterward',
        items: [
          'Write down what worked and what to change, while it is fresh.',
          'Tell us how it went through the contact form.',
          'Send a short thank-you note to your staff contact.',
        ],
      },
    ],
    card: { heading: 'Teaching it yourself?', text: 'Read the guide for running a hands-on class.', button: 'Teach it yourself', href: '/teach' },
  },
  consent: {
    title: 'Photo and video consent form',
    description: 'A template consent form for taking photos or video during a lesson visit. Print it and fill it in by hand.',
    intro:
      'We only take photos or video of a learner with written consent from that person, and from the facility. This is a template. Print one for each person. Bring the signed copy to the facility, and keep a copy yourself.',
    notLegal: 'This form is not legal advice. Please have a parent or guardian, and the facility, read it before you use it.',
    print: 'Print this form',
    fields: {
      project: 'Project',
      projectValue: 'Byte-Sized Buddies, a student-led volunteer project',
      facility: 'Facility name',
      name: 'Name of the person in the photo or video',
      date: 'Date',
    },
    chooseHeading: 'What the person agrees to (tick any that apply)',
    choices: [
      'A photo of me may be taken during the lesson.',
      'A short video of me may be recorded during the lesson.',
      'The photo or video may be shown on the Byte-Sized Buddies website.',
      'The photo or video may be used in printed materials, like a flyer.',
    ],
    promisesHeading: 'Our promises',
    promises: [
      'You may say no. Saying no will never change how we treat you or the lesson you receive.',
      'You may change your mind at any time. Tell us, and we will take the photo or video down.',
      'We will not put your full name next to a photo or video unless you ask us to.',
      'We will not take photos of passwords, personal messages, or the screens of private devices.',
    ],
    signHeading: 'Signatures',
    sign: {
      person: 'Signature of the person',
      guardian: 'Signature of a guardian or staff member, if the person cannot sign',
      volunteer: 'Volunteer name and signature',
      facility: 'Facility representative name and signature',
    },
  },
  teach: {
    title: 'Teach it yourself',
    description: 'Free, ready-to-use guidance for teaching technology to older adults in your own community.',
    lessonsButton: 'See the free lessons',
    tellButton: 'Tell us how it went',
    card: { heading: 'Get the free lessons', text: 'Every lesson has slides, a teacher guide, a worksheet, and a large-print handout.', button: 'See the free lessons', href: '/lessons' },
  },
  privacy: {
    title: 'Privacy',
    description: 'What Byte-Sized Buddies collects, why, who sees it, and how long we keep it.',
    card: { heading: 'A question about your information?', text: 'Ask us. Your answer appears at a private link only you have.', button: 'Ask a question', href: '/ask' },
  },
  license: {
    title: 'License',
    description: 'How you may use, print, adapt, and share Byte-Sized Buddies lessons.',
    card: { heading: 'Use the lessons', text: 'Print them, adapt them for your learners, and share them. Please credit Byte-Sized Buddies.', button: 'See the free lessons', href: '/lessons' },
  },
  notFound: {
    title: "We can't find that page",
    text: 'The link may be old, or the address may have a typing mistake. Everyone ends up in the wrong place sometimes.',
    button: 'Go to the home page',
  },
} as const;
