// All user-facing words for the shared page frame live here, so they can be translated later.
export const copy = {
  siteName: 'Byte-Sized Buddies',
  tagline: 'Learn it. Try it. Keep it.',
  skipLink: 'Skip to main content',
  logoHomeLabel: 'Byte-Sized Buddies, home',
  nav: {
    label: 'Main',
    items: [
      { label: 'Lessons', href: '/lessons' },
      { label: 'For senior homes', href: '/for-senior-homes' },
      { label: 'Ask a question', href: '/ask' },
      { label: 'Teach it yourself', href: '/teach' },
      { label: 'About', href: '/about' },
    ],
    visit: { label: 'Request a visit', href: '/for-senior-homes#contact' },
    menuOpen: 'Menu',
    menuClose: 'Close menu',
  },
  footer: {
    line: 'Byte-Sized Buddies · Free to print and share · [YOUR WEBSITE]',
    studentLed: 'Student-led volunteer project.',
    linksLabel: 'About this site',
    links: [
      { label: 'Privacy', href: '/privacy' },
      { label: 'License', href: '/license' },
    ],
  },
  form: {
    required: '(required)',
    optional: '(optional)',
    errorPrefix: 'Problem:',
    summaryTitle: 'Please fix these before sending:',
    sending: 'Sending',
    notConnected: "This form isn't connected yet, so nothing was sent. Please check back soon.",
    privacyHelper: "Please don't include passwords, medical details, or bank information.",
    errors: {
      name: 'Please tell us your name.',
      facility: 'Please tell us the name of your facility.',
      email: 'Please enter an email like name@example.com.',
      questionShort: 'Please write at least 5 characters.',
      questionLong: 'Please keep your question under 2,000 characters.',
    },
  },
  mission:
    'Free, patient, hands-on technology lessons for older adults, and free materials for anyone who wants to teach them.',
  home: {
    title: 'Byte-Sized Buddies',
    description:
      'Free, patient, hands-on technology lessons for older adults, and free materials for anyone who wants to teach them.',
    heroButtons: { visit: 'Request a visit', lessons: 'Get free lessons' },
    visit: {
      heading: 'How a visit works',
      steps: [
        { title: 'Learn it.', text: 'We start with a short, friendly slideshow. One idea at a time.' },
        { title: 'Try it.', text: 'Everyone practices on their own device, with help beside them.' },
        { title: 'Keep it.', text: 'Each person takes home a large-print handout to remember what they learned.' },
      ],
    },
    lessons: {
      heading: 'What you can learn',
      emptyTitle: 'Our first lessons are on the way',
      emptyText: 'Every lesson will be free to download, print, and share. Please check back soon.',
    },
    homes: {
      heading: 'For senior homes',
      text: "We bring everything. You provide a space, a TV or projector if you have one, and a few residents who want to learn. There's no cost, ever.",
      needHeading: 'What we need from you',
      needs: ['A room', 'A screen or TV (optional)', 'Wi-Fi, if you have it', 'A staff contact person'],
      button: 'Ask about a visit',
    },
    free: {
      heading: 'Free for everyone',
      text: 'Want to teach these lessons in your community? Everything here is free to download, print, and adapt. Read the teacher guide, bring a friend, and tell us how it went.',
      button: 'Teach it yourself',
    },
    promise: {
      heading: 'A promise to families and staff',
      items: [
        'We never ask learners to type a real password in class.',
        'We use practice accounts.',
        'We take photos and video only with written consent.',
        'Our lessons are free, always.',
      ],
    },
  },
  homes: {
    title: 'For senior homes',
    description:
      'What a Byte-Sized Buddies visit looks like, what we need from you, and how to ask for a visit. Every lesson is free.',
    intro:
      "We bring everything. You provide a space, a TV or projector if you have one, and a few residents who want to learn. There's no cost, ever. Lessons run about 45 minutes. Each lesson comes with a large-print handout for every learner.",
    flowHeading: 'How a visit works',
    flowIntro: 'Each visit is one lesson, about 45 minutes long.',
    flow: [
      'Welcome and a warm-up question (three minutes)',
      'Learn it: a short slideshow (10 minutes)',
      'Try it: guided practice on each person\'s own device (20 minutes)',
      'Worksheet, then teach it back to a neighbor (seven minutes)',
      'Keep it: a large-print handout and a take-home challenge (five minutes)',
    ],
    needHeading: 'What we need from you',
    needs: ['A room', 'A screen or TV (optional)', 'Wi-Fi, if you have it', 'A staff contact person'],
    bringHeading: 'What we bring',
    bring: [
      'Everything we need, free of charge',
      'A large-print handout for every learner',
      'A short slideshow and a one-page worksheet',
      'Practice accounts, so no one types a real password',
    ],
    formHeading: 'Request a visit',
    formIntro: "Tell us a little about your community. We'll write back to plan a time.",
    fields: {
      name: 'Your name',
      facility: 'Facility name',
      role: 'Your role',
      email: 'Email',
      phone: 'Phone',
      learners: 'Approximate number of learners',
      devicesLegend: 'Devices they usually use',
      times: 'Best days and times',
      more: 'Anything else we should know',
    },
    devices: [
      { value: 'iphone', label: 'iPhone' },
      { value: 'android', label: 'Android phone' },
      { value: 'tablet', label: 'Tablet' },
      { value: 'computer', label: 'Computer' },
      { value: 'not_sure', label: 'Not sure' },
    ],
    submit: 'Send request',
    success: {
      title: 'Thank you',
      text: "We'll reply within two days. We'll write to the email you gave us.",
      again: 'Send another request',
    },
  },
  ask: {
    title: 'Ask a question',
    description:
      'Have a quick question about a device or a lesson? Ask here. Your answer appears at a private link only you have.',
    intro:
      "Have a quick question about a device or a lesson? Tell us what you're seeing. Please don't include passwords, medical details, or bank information.",
    fields: {
      name: 'Your name',
      facility: 'Facility',
      email: 'Email',
      emailHelper: 'So we can send your answer.',
      deviceLegend: 'Which device is it about?',
      urgencyLegend: 'How soon do you need an answer?',
      question: 'Your question',
      questionHelper: 'Write between 5 and 2,000 characters.',
    },
    devices: [
      { value: 'iphone', label: 'iPhone' },
      { value: 'android', label: 'Android phone' },
      { value: 'tablet', label: 'Tablet' },
      { value: 'computer', label: 'Computer' },
      { value: 'not_sure', label: 'Not sure' },
    ],
    urgency: [
      { value: 'whenever', label: 'Whenever' },
      { value: 'this_week', label: 'This week' },
      { value: 'before_next_visit', label: 'Before our next visit' },
    ],
    submit: 'Send question',
    success: {
      title: 'We got your question',
      linkLabel: 'Your private answer link',
      save: "Save this link. It's the only way to find your answer.",
      emailNote: "If you gave an email, we'll also send the link there.",
      copy: 'Copy link',
      copied: 'Link copied.',
      copyFailed: 'Your browser could not copy it. Select the link and copy it by hand.',
      again: 'Ask another question',
    },
  },
  viewer: {
    label: 'Slides',
    previous: 'Back',
    next: 'Next',
    counter: (n: number, total: number) => `${n} of ${total}`,
    announce: (n: number, total: number, title: string) => `Slide ${n} of ${total}: ${title}`,
    progress: 'Slide progress',
    fullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
    blank: 'Blank screen',
    unblank: 'Show the slide',
    blankNote: 'The screen is blank. Press B or the button to show the slide.',
    print: 'Download slides as PDF',
    keys: 'Tip: click the slide, then use the arrow keys, Space, Home, End, B for blank, and F for full screen.',
    timerStart: (minutes: number) => `Start ${minutes}-minute timer`,
    timerPause: 'Pause timer',
    timerReset: 'Reset timer',
    timerDone: 'Time is up.',
    minutes: 'minutes',
    notes: 'Speaker notes',
    noNotes: 'No notes for this slide.',
    noSlides: 'This lesson has no slides yet.',
    tryIt: 'Try it',
    missingImage: 'Picture not found',
    recapTitle: 'Today you learned',
  },
  answer: {
    title: 'Your answer',
    description: 'Read the answer to your question.',
    loading: 'Looking for your answer',
    notConfigured: "This page isn't connected yet. Please check back soon.",
    notFoundTitle: "We can't find that link",
    notFoundText:
      'The link may be missing a few letters. Try opening it again from where you saved it. You can also ask your question again.',
    askAgain: 'Ask a question',
    statusLabel: 'Status',
    status: {
      new: 'Received',
      in_progress: "We're working on it",
      answered: 'Answered',
      closed: 'Closed',
    },
    greeting: (name: string) => `Hello ${name}`,
    questionHeading: 'Your question',
    answerHeading: 'Our answer',
    waiting: "We haven't answered yet. Please come back to this page later. Your link keeps working.",
    videoTitle: 'Video answer',
    videoOpener: 'Hello',
    videoMain: 'Your answer',
    videoCloser: 'Goodbye',
    errorText: 'Something went wrong while looking for your answer. Please try again in a few minutes.',
  },
  lessons: {
    title: 'Free lessons',
    description: 'Free technology lessons for older adults. Download, print, adapt, and share.',
    intro: 'Every lesson comes with a teacher guide, a slideshow, a worksheet, and a large-print handout. All of it is free to download, print, and share.',
    emptyTitle: 'Our first lessons are on the way',
    emptyText:
      'Each lesson will come with a teacher guide, a slideshow, a worksheet, and a large-print handout. All of it will be free to download, print, and share.',
    teachButton: 'Teach it yourself',
    loading: 'Loading lessons',
    loadError: "We couldn't load the lessons. Please try again in a few minutes.",
    filterLabel: 'Show lessons for',
    chips: { all: 'All', iphone: 'iPhone', android: 'Android', beginner: 'Beginner', intermediate: 'Intermediate' },
    searchLabel: 'Search lessons',
    searchHelp: 'Type a word from the title or topic.',
    noMatches: 'No lessons match. Try a different word, or choose All.',
    count: (n: number) => `${n} ${n === 1 ? 'lesson' : 'lessons'} shown`,
    week: (n: number | null) => (n === null ? 'Lesson' : `Week ${n}`),
    minutes: (n: number) => `${n} minutes`,
    seeAll: 'See all lessons',
  },
  player: {
    play: 'Play the video',
    playParts: (n: number) => (n === 1 ? 'Play the video' : `Play the video (${n} parts)`),
    partsIntro: (labels: string[]) => `This video has ${labels.length} parts: ${labels.join(', ')}. They play one after another.`,
    privacy: 'The video plays from YouTube. Nothing loads from YouTube until you press Play.',
    part: (n: number, total: number, label: string) => `Part ${n} of ${total}${label ? `: ${label}` : ''}`,
    prev: 'Previous part',
    next: 'Next part',
    partsLabel: 'Choose a part',
    goTo: (n: number, label: string) => `Part ${n}${label ? `: ${label}` : ''}`,
    ended: 'That was the last part.',
    again: 'Watch from the start',
    captions: 'Captions are on when the video has them. Press CC in the player to turn them off.',
    frameTitle: (title: string, label: string) => `${title}${label ? `: ${label}` : ''}`,
  },
  lesson: {
    loading: 'Loading the lesson',
    notFoundTitle: "We can't find that lesson",
    notFoundText: 'The lesson may have moved, or the link may have a typing mistake. You can see every lesson in the library.',
    library: 'Go to the lessons',
    objectives: "What you'll be able to do",
    downloads: 'Downloads',
    downloadsNone: 'The downloads for this lesson are not ready yet.',
    pdf: 'PDF',
    slidesHeading: 'Preview the slides',
    videoHeading: 'Video',
    guideHeading: 'Teacher guide',
    noGuide: 'The teacher guide for this lesson is not ready yet.',
    license: 'License',
    licenseLink: 'How you may use this lesson',
    tell: 'Tell us how it went',
    printGuide: 'Print this page',
    adminDraft: 'This lesson is a draft. Only you can see it.',
  },
  about: {
    title: 'About',
    description: 'Byte-Sized Buddies is a student-led volunteer project that teaches technology to older adults.',
  },
  teach: {
    title: 'Teach it yourself',
    description: 'Free, ready-to-use guidance for teaching technology to older adults in your own community.',
    lessonsButton: 'See the free lessons',
    tellButton: 'Tell us how it went',
  },
  privacy: {
    title: 'Privacy',
    description: 'What Byte-Sized Buddies collects, why, who sees it, and how long we keep it.',
  },
  license: {
    title: 'License',
    description: 'How you may use, print, adapt, and share Byte-Sized Buddies lessons.',
  },
  notFound: {
    title: "We can't find that page",
    text: 'The link may be old, or the address may have a typing mistake. Everyone ends up in the wrong place sometimes.',
    button: 'Go to the home page',
  },
} as const;
